---
title: "日记｜如果要有100个纪念日"
date: "2026-08-08"
categories: [diary, 中文]
description: "为了防止把这辈子最处心积虑泡别人的过程忘个精光而写的流水账"
---

一个甚至两个绝望的社恐

## 2023

### Aug-Dec

- 入学。

- 加入实验室。人不能谈办公室恋爱所以悲剧和喜剧从此开始。

- 因为初试dating app大失败所以陷入到了恐怖的sexuality焦虑中，决定谈一次恋爱来判断自己到底是不是无/有性恋。

## 2024

### Feb-Mar

- 春节聚会。对方很cute^^ 帮我喝酒^^

- 春假，处心积虑地发起系内hiking，对方说要参与，开心。hiking的时候对方带了水果分给大家吃，好细心，喜欢。我说爬得好累，对方请大家停下来等等我，可爱。被拍了在同一张画幅里的照片，偷乐。最后通过一些哎呀我这里更加顺路一些呀之类的话术，成功让对方坐在我的副驾驶回家了，假装不经意偷摸播放There is a light that never goes out，心满意足。

### Apr-Jul

- 对方说可以带我去看看学校打羽毛球的地方。于是美美一起下班，看完场地以后就去吃了学校旁边中餐馆的酸菜鱼，辣得我得涕泪横流，形象尽失，并且聊到兴起处忍不住把正在听的摇滚乐和正在搞的产品全部和盘托出，从此以后就再也没有形象了（。总之这是第一次real conversation。

- 真的出来打羽毛球，虽然占用了人家匹克球的场地。处心积虑穿搭了，但整个过程中还是紧张兮兮，中场休息的时候不敢对视也不敢坐得太近……session结束，鼓起勇气约对方出来到inner harbor逛街看海。准备下海鲜馆子却被告知要等位，于是在水族馆前面闲逛。从来没有经历过这种情况所以大脑过载不知道说什么，只能说一些啊啊我们来玩猜词游戏吧之类的傻话，最后在海边双人椅上尴尬地坐在被把手分开的两边，哈哈……吃完饭以后对方在Cheesecake factory陪我等车回家。嗯这个Cheesecake factory未来还会多次出现。

- 某次实验失败被老板在组会上阴阳了，于是拜托对方来和我话聊。在学校咖啡馆前面一会儿哭一会儿怒骂一会儿思考人生，接着上天台一会儿哭一会儿怒骂一会儿思考人生，最后去harbor一会儿哭一会儿怒骂一会儿思考人生。对方带我去吃了意大利菜……超正宗的意大利千层面，意思是好吃的同时也齁得慌。结束以后又拜托对方到Cheesecake factory陪我等车回家。

- 这段时间里应该还有几次出来打羽毛球而我的勇气消失了所以不敢约后续逛街的session。

- 生日，对方送了我一张喜欢的乐队的vintage海报！好用心的礼物！喜悦。

- 六月有一次打完球，正巧下阵雨，一开始在体育馆里一起躲雨，欲盖弥彰地打开笔记本工作，结果雨越下越大，对方掏出了一把小绿伞……一起在东海岸版本的梅雨里撑伞等车时不由地痴了，回去迅速画了一张画，发了朋友圈。对方没有表示。一怒之下怒了一下。

- 4th of July，试图暗示对方出来一起看烟花，失败了！觉得是自作多情了，第一次放弃。

- 对方生日，绞尽脑汁不知道送什么好，最后送了一盒拼字游戏。

- 申请开始，封心锁爱。

### Aug-Dec

- 中秋聚会，对方带来的卤牛肉很好吃，又爱上了。

- 圣诞聚会，对方很cute^^

## 2025

### Jan-Feb

- 申请结束，又可以了。

- 看了Alcest表演，神秘地被点通了情窍……

### Mar-May

- 邀请对方一起去给爱伦坡扫墓。精心穿搭，穿了黑色的裙子，黑色的袜子，黑色的皮鞋，甚至还戴了墨镜，装装地坐在Mount Vernon的哥特大教堂前面看电子书。对方也精心穿搭了，还带了水给我喝，满意。樱花季节的巴尔的摩很漂亮，dokidoki，街道很危险，依然dokidoki。在墓园里竭尽全力显摆自己丰富的历史文化知识，鼓起勇气请对方给我拍照，虽然摆造型的时候还是僵死了。回去的路上先是假装不经意暗示对方可以一起再去MICA逛逛，没get到，失败。于是竭尽全力暗示对方邀请我一起去首都看樱花，还是没get到，失败。一怒之下怒了一下，转而邀请五月份一起去看fontaines DC。

- 试图约再一起去打羽毛球，结果学校体育馆施工，健身房临时改到了别的场地，羽毛球场地就没了。遂邀请对方再次到Inner Harbor散步。从医学院开始往南走，走了好久好久，走到Patterson Park，在枯萎的芦苇丛中听red-winged blackbird的求偶叫声，看鸭子在尚且寒冷的春水中游泳……走到Fell's point，吃了冰激凌，逛了唱片店……一直一直在聊天，聊到以后想去哪里旅行，聊到未来，从水族馆前面漂亮的小桥走过……本来想就这样各自回家，在Cheesecake factory等车的时候还是痴了，请对方一起去Hampden吃羊肉（阿富汗菜）。阿富汗菜类似于新疆菜，羊肉饭里有浓浓的汁水和各种果干。夜色渐深，对方似乎也痴了，开始试图谈论感情话题。……但是我僵死了。对方说我是不是吃多了晕碳。好吧！最后在冰激凌店里并肩坐着等车，我欲言又止，止言又欲，还是僵死了，只能愤恨地独自一个人从Hampden坐回Mount Vernon。到底在做什么呀！！

- 一起去看fontaines DC，精心穿搭，对方也精心穿搭了，满意。过去的火车上太紧张以至于一直在看kindle，甚至在演出开始前等待的过程中也太紧张所以掏出kindle一直看，现在回忆起来真想一巴掌把自己拍死。演出很完美，结束以后一起打车回家，一小时的车程，沉默中气氛略微暧昧，我又僵死了，遂开始吐槽同事。又想一巴掌把自己拍死。

- 系里的毕业聚会。KTV里尽量坐在对方旁边，打了德扑。不知是德扑太令人心跳加速还是坐在对方身边这个事实太令人心跳加速，总之玩了两局就落荒而逃，跑到唱歌那桌去了。

- 毕业典礼。帮对方和哥们儿拍了照片。

- 实验室的毕业聚会。给每个人写了贺卡。结束的时候和对方一起乘公交车回去，走过空荡荡的医院走廊，等车时有一搭没一搭地聊着，车到了，鼓起勇气直接坐在对方旁边。没有表示。一怒之下怒了一下。这次不是觉得我自作多情而是觉得对方是个木头。第二次放弃。

### Aug-Dec

- 重返米国。

- 怀念good old days以至于夜夜哭泣，于是对自己承认又爱上了，决定继续织网，等待对方重返米国就收网。

- 终于向有恋爱经验的亲友请教，获取了一些建议。

- 试图通过微信保持联系，或者不如说保持谄媚。对方态度暧昧不明，一直硬发🥺表情也不是个办法，焦躁不安……

## 2026

### Jan

- 对方重返米国。

- 被刺激了一怒之下直接收网，打电话表白，对方羞答答地接受了，于是喜悦地转成视频掏出吉他大唱情歌，分别是Don't Break My Heart和Vapour Trail。对方说自己太怂不敢懂我的暗示。我真是服了。暗示很坏。直球很好！但我确实不想谈办公室恋爱所以只能暗示！一旦时机成熟可以直球了就直球上了。

### Feb-Aug

约会，牵手，亲嘴，享受*劳动成果*……

- 情人节对方来看我。飞机半夜十二点才到，说好了要一见面就抱抱但还是生疏地隔着半米从机场走了10分钟路回家，最后勇敢打破尴尬的气氛，拉着对方的手在宿舍楼下坐了好久，一直抱抱一直说话，直到凌晨两三点。第二天起了大早，去市区吃了饭，逛了学校和周边。糖果店好漂亮，而Wabash River完全冻住了。学校里有人在发情人节的玫瑰花，我们牵着手所以获赠了一支粉红色的，开心。回到宿舍给对方做了番茄肥牛饭，又掏出吉他大唱情歌，直到深夜。对方唱歌很好听。给我推荐了方大同版本的《红豆》，也很好听。晚上在出租车前面告别之前忍不住亲了对方脸颊一口，对方着急慌忙地说我也要亲一口，亲在了我头发上ww

- 四月份去了对方的学校。飞机延迟了好久，计划全打乱了；但最终还是顺利到达！先是逛了校园，四月在高纬度地区还是早春，对方的学校里樱花随着小雨纷纷扬扬地落下，很多刚生出来的小兔子在湿润的草地上跑跑跳跳，非常浪漫。忍不住想在教学楼前面的樱花树下亲他但是忍住了（当天晚些时候还是亲到了^^）。去冰激凌店吃了对方学校农学院自产的冰激凌，很好吃。晚上在一家不错的餐馆里吃了很有格调的晚餐，对方羞涩地说一直觉得这个地方很适合约会，提早订了位置。吃了西班牙海鲜饭，侍者大叔一直过来想确认到底做得好不好吃，我吃得有那么慢吗！ww 桌上有一小束金黄的十字花科小花，查了一下，名叫伯利恒之星。第二天下午去对方家里呆了一会儿，对方做了缺德舅的鲈鱼还有干煸四季豆，很好吃！好幸福！就喜欢做饭好吃的人。还跟我妹视频通话了。

- 五月份在芝加哥玩（#1）。芝加哥真美！带了Walmart买的果味气泡酒，倒在喝清酒的小杯子里，两个人一起喝了，按理说酒精浓度也不高呀！人人自醉了。第二天中午去吃了龙虾卷，然后沿着芝加哥漂亮的沿河步道散步，观察着一路上形形色色的人（和小狗），一直走到摩天轮旁边；可惜已经累得精疲力竭，没能看到夜景。晚上去河边的一家酒馆“Beatnik”吃了希腊菜，很好吃。第二天离开前匆匆逛了世纪公园，看到了the Bean和那个会从嘴里喷水的大雕像——虽然24年自己有来过，但和男朋友一起来还是很开心。

- 生日的时候获赠了Nikon的望远镜，8*42的配置，附有背带和十字式的harness，观鸟如虎添翼！对方说有在美观和实用中犹豫，但最后选择了实用。哎，但我觉得Nikon的设计也很漂亮嘛！

- 六月份在芝加哥玩（#2）。芝加哥的夏天尤其美，但是酒店尤其贵，于是住在了ORD旁边。下午乘地铁去市区，有人陪着的话，坐又长又晃的Blue line也不觉得难受了！我们从世纪公园逛到northerly islands，一路上都在欣赏蓝天白云下的密歇根湖和芝加哥城区天际线。看到了各种小鸟，世纪公园里满地都是加拿大鹅暗绿色的鹅屎，northerly islands的preserve里有一小块都是北美原生植物的prairie，繁花盛开，dickcissel和savannah sparrow在栅栏上歌唱。晚饭吃了世纪公园旁边的泰国菜。第二天去机场边的outlet随便逛了逛，结果差点没赶上飞机w。开玩笑说走不了的话就留在我这里好了。

- 对方生日，送了对方一个行李箱。

- 离开之前对方又来看我，黏糊地度过了几天。

- **果然很可爱**。很supportive，情绪很稳定，像一只温暖的母鸡。看到对方的脸、听到对方的声音就觉得很幸福。
