---
title: "年终总结｜2024 Merry Xmas, What have you done?"
date: "2024-12-24"
categories: [year-end recap, 中文]
---

::: callout-note
摘自日记，作为存档。
:::

今天有点失眠，就把前几天开的天窗全部补上吧，权当作2024年的总结。

约翰列侬曾经曰过：

> So this is Christmas, and what have you done?
>
> Another year over, a new one just begun.

那我这一年做了什么呢？感觉可以从一个贯穿了这本日记的主题说起……

## 你怎么又，又，又去看RIDE了？

这次因为是在著名的场地——华盛顿的9:30 Club看的，所以我本来期待挺高的。暖场的Rocket也相当不错，音效震撼到我必须掏出耳塞来防止自己彻底聋掉的地步。但不知为何，RIDE反而拉垮，最拉垮的就是Andy Bell，不仅跑调，Leave Them All Behind solo的吉他推弦还没推上去，我心都碎了。幸好🎵宽阔的肩膀承载了我的悲伤，让我意识到“你的吉他英雄也是人，也是可能拉垮的”这个事实，在2024的末尾避免了一脚踏入个人崇拜的深渊……

总之，19天过去了，我已经调理好了。🎵还帮我抢到了Mark的setlist！我们一起拍了合照。去华盛顿当天还在火车站里看见了乌克兰的圣歌合唱团，听了一会儿他们的表演。其实Mark和Andy还和我们开玩笑，说要给我们唱圣诞颂歌来着。怎么没唱！

---

Put RIDE aside，这一年是自己和朋友们努力寻找一种“成年后的生活方式”的一年。无论是身边的实验室友人、宽老师和🎵，还有隔着网线能注视到的友人，比如阿闲老师……

说白了就是“这个人生我想怎么活”的问题。今年最大的进步就是明确了“我完全不想管别人是怎么活的，我爱怎么活就怎么活”。满足了自己对友谊、亲密关系、自由以及为了保证自由所需要的经济独立、创造欲（aka搞同人和画画）的需求以后，其实人就能活了，然后再慢慢地寻找人生的意义。之前开玩笑说人要满足自己对成就感的需求，得有一个主业，一个副业，一个主爱好，一个副爱好，这样全部一起搞砸的可能性就比较低，就能随时随地找到一个杯子来吸一口多巴胺。

虽然也能理解遵从社会规范的“时钟”去把恋爱结婚当成任务完成能给人带来现实上的好处，但我真的很难强迫自己去做不想做的事。并且我逐渐开始觉得恋爱本质上和兴趣爱好一样，是一个用来消磨时间的东西，毕竟另一个人类其实也是一个和，你感兴趣的东西，比如，乐队（。）一样越研究越有的东西。就是涉及到了人的话，在这个过程中就不可避免地会对对方以及自己产生伤害……

## 本年度人际交往大进步

1. **和师长相处正常化**

- 标志性事件：能和导师冷静、客观、熟练地沟通工作目标，工作进度etc，并且能开开玩笑。

2. **和朋友hang out频率升高**

- 标志性事件：春假组织hiking，暑假和朋友们开车去周边玩，和朋友去看各种演唱会。

3. **和网友关系更进一步**

- 标志性事件：和网友一起相濡以沫地搞RIDE。当然这主要是因为网友也比较热情。网友有灰鱼、脖子、樱桃还有线下随机相遇的“骑友（RIDEmate）”。

4. **和异性的相处正常化**

- 标志性事件：和（后来的男朋友）当了将近大半个月的羽毛球友，散了步，吃了饭，聊了天啥的，还收到了生日礼物（是RIDE的海报。我真的受不了了。浓度太高了。）

## 总结经验

1. 敞开自己。我现在逐渐发现这个世界上大多数人都觉得我蛮有趣的——只要我敢把“这一面”表现出来。

2. 主动，主动，主动。千万别矜持。

3. 树立边界。别人让你不舒服了，就礼貌又清楚地告诉ta，别心软。

4. 不得不承认蛮多人际关系的展开都和RIDE有关，让我们继续爱RIDE！

好了，感觉暂时也没什么想说的了，再写下去就有点强求了。圣诞快乐，新年快乐，顺便拜个早年。无论命运会把我带向何方，2024年都会是值得铭记的一年，因为今年自己在美国真正地踏出了成年人生活的第一步……啊，忘了说，今年也逐渐接受了“在不知道要持续多久的‘现阶段’我都不可能放弃搞同人”这一事实，或许是因为室友也是一个同人女（。

哎，我感觉未来回忆起2024年，说不定会第一个想起和🎵、浣熊老师眼巴巴看RIDE的场景，真是完蛋！
