---
title: "北京·乌兰察布·大同｜西北自驾游"
date: "2023-07-04"
categories: [travel, roadtrip, 中文]
---

## 游记

前几天🎵和我说她在旅程结束后的第一天就发烧了，烧退后感觉旅行仿佛蒙了一层雾般，怕回忆不起来当时的心境了。深有同感。其实作为不是职业旅行者的一般人，是没什么必要去写非常详尽的旅游攻略/游记的，写成那种网红风的“推荐”或“踩雷”也不是我的风格。就稍微写写“自驾”本身和三个城市给人的感受好了。不要太野心勃勃，不然就会变成懒得动笔（笑

其实我目前最想写的是音乐。感谢那个第一个想出来在汽车上搭载音乐播放器的天才！一路上听了无数歌，但果然印象最深的还是Oasis。无论什么路况，无论多么晕头转向或昏昏欲睡，放到Live Forever的时候都会记着合唱的。在大同的第一天在旅馆休息，我脑子里正在循环播放Some Might Say，然后就听到🎵也在唱Some Might Say…心电感应一般，就很兴奋，也有被浪漫到！

> Can I ride with you in your B.M.W.?

行车中最爱的粥曲变成了Stand by Me。Noel的吉他在这首里极好，Liam稍稍沙哑的嗓音也很好。也和🎵探讨过为何会有胆子自驾，结论是对对方驾驶技术的信任和一点“室友的小默契”（笑）。总之，开车体验还是很愉快的。和之前无数次坐在对方副驾驶的体验一样。

自驾和传统旅游最不同的一点，可能就是对地形变换的深刻体验。这是什么山，什么河？每一次开到山路或者下坡的时候都会忍不住去想。从大同回京的路上，右边绵延不绝的是恒山，正在翻越的是阴山，需要开25公里连续下坡的是环绕首都的燕山。植被的类型、覆盖率，都会随着道路的延伸发生变化。

乌兰察布人很少很少。应该本来就不是旅游城市，但天很蓝草很绿，城市里的各种设施也又新又完备。但人真的太少了，有的时候就觉得很超现实……人口密度只有北京的1/45！开在公路上的时候就觉得人类真伟大啊，这么荒凉的地方也又完备的公路系统，但又杞人忧天地开始担心，汽车发明到现在也不过一百多年，这么完美、漂亮的公路说不定在未来几十年内就会和纸媒一样被淘汰呢……火山公园很有意思，在里面猴性大发，明明月经Day1但完全不觉得累，在每个山爬上爬下捡石头玩……并且风很大！印象非常深刻的是一种大蚱蜢，枯黄色的，飞起来和小型战斗机一样咔咔作响，有点吓人！内蒙古的草原没有蚊子，但有不少大大小小的蚱蜢和苍蝇。

大同是个很特别的城市。乌-大段是我开的，就发现公路逐渐从沥青路变成水泥路。我心里就想，不会吧，路修成这样，难道比内蒙古还穷吗？后来查到水泥路是为了防止运煤车把路面压坏而特意修的，也有道理，但就是对小轿车太不友好了，开到80码以上能把人颠得吐出来。逐渐离市中心近了，就看到一架又高又长的运煤高架桥横在公路上方，挺符合自己对西北工业城市的刻板印象的……但进城以后就感觉不一样了。古城内部的古建筑看得出来都是在用心去维护的，夜晚在灯光映衬下很美。石窟和晋华宫地下游的景点都做得非常用心，地下游景点甚至可以说是非常完善、优秀的煤炭开采科普基地。云冈石窟的“本体”和书里写的一样震撼，让人觉得一些奇迹是必须得用双眼去感受它们的力量的……当天很热，石窟又高又窄，仰望佛像的时候甚至觉得一阵晕眩。大同市博物馆是非常好的北魏文化展示基地，尤其是司马金龙墓出土的文物，风化也很少。甚至在这里偶遇了本科的另一位同学！总体来说可以感受到城市规划者的用心。只是车开得太野，停得太乱，在这一方面有非常多可以改进的空间。

首都的话，印象最深刻的就是夜游颐和园。非常美，日落很有感觉，还见到好多雨燕。

------------------------------------------------------------------------

## 行程

-   S 6/25 家 -\> **北京**（南站）
    -   于“普希金文学餐厅”吃晚饭

-   M 6/26 北京（海淀）
    -   首钢冬奥园
    -   颐和园

-   T 6/27 北京（朝阳）
    -   798艺术街区逛街
    -   看电影《闪电侠》

-   W 6/28 北京 -> （张家口） -> **乌兰察布**（集宁）
    -   入住白象山庄
    -   参观乌兰察布博物馆
    -   观看“天宫”划过天空

-   T 6/29 乌兰察布（集宁） -> （察右后旗） -> **大同**（古城）
    -   驱车前往乌兰哈达火山地质公园，参观火山（黑脑包，北炼丹炉，南尖山）
    -   入住云冈美高大酒店
    -   夜游大同古城
    -   吃了网红店“紫泥369粗粮季”

-   F 6/30 大同（古城） -> （云冈镇） -> （古城）
    -   参观晋华宫国家矿山公园（井下游、博物馆、矿工食堂）
    -   参观云冈石窟1-20号窟

-   S 7/1 大同（平城区） -> （张家口） -> **北京**（海淀）
    -   参观大同市博物馆

-   S 7/1 北京（南站） -\> 家

## 自驾游总结

- 总里程：1036.5km（我开了494.5km）

- 车：SUV

- 导航：高德地图（林志玲语音版）

- 路程：G6 -> G55 -> S30/S32/S10 -> S380
     -   S6京藏高速：难开的八达岭段，极为繁茂的行道树
     -   G55二广高速：很美，大同段是水泥路
     -   S30孙右高速/S32宣大高速/S10张右高速
     -   S380京礼高速：多隧道
